name: Bradbury's Laboratory
favicon: null
layout_spectrum: 0.00867
typography_spectrum: 0.75048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0d0a'
    - '#c1ad8c'
    - '#63412f'
    - '#757062'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
